const actionTypes = {
  GET_SCORE_REQUESTED: 'GET_SCORE_REQUESTED',
  GET_SCORE_REJECTED: 'GET_SCORE_REJECTED',
  GET_SCORE_FULFILLED: 'GET_SCORE_FULFILLED',

  START_GAME: 'START_GAME',
  END_GAME: 'END_GAME',

  ADD_SCORE_REQUESTED: 'ADD_SCORE_REQUESTED',
  ADD_SCORE_REJECTED: 'ADD_SCORE_REJECTED',
  ADD_SCORE_FULFILLED: 'ADD_SCORE_FULFILLED',

  SCORE_ADDED: 'SCORE_ADDED'
};

export default actionTypes;
